### ISSUE TITLE
Service[rpcbind.service]/enable: enable changed 'false' to 'true' on every run.

### ISSUE THREAD

**Issue by wardhus** [derdanne/puppet-nfs#55] opened 2017-03-15 10:26 UTC
Hello,

On CentOS 7 I get this in every run:
`Debug: Executing: '/bin/systemctl is-enabled rpcbind.service'
Notice: /Stage[main]/Nfs::Client::Service/Service[rpcbind.service]/enable: enable changed 'false' to 'true'`

If i run is-enabled:
`myhost:~# systemctl is-enabled rpcbind.service
indirect`

There are a few related issues:
https://tickets.puppetlabs.com/browse/PUP-7163
https://tickets.puppetlabs.com/browse/PUP-6370
https://tickets.puppetlabs.com/browse/PUP-6759

After reading them I believe enabled for rpcbind should be set to false

**Comment by wardhus** [comment] 2017-03-15 12:17
Hello, The PR above fixes this issue for RHEL7, defaults for other OS's are unchanged.

**Comment by derdanne** [comment] 2017-03-15 12:57
Hi, thanks for the PR. 

Could you please check your commit of init.pp - you've changed the variable name of $server_service_enable  to $server_services_enable, and most of the tests are not passing.

**Comment by derdanne** [comment] 2017-03-15 16:04
Hi, thanks for the fix, but the tests are still not passing, can you please have a look at what is failing? If you need some help, just write me.

**Comment by dylex** [comment] 2017-08-17 18:18
This still seems to be happening with 2.0.4. It looks like 8819a8ca0f5cf2a55c29e80c708f497689bfffa6 reverted the "fix" to this.  A better fix may be to switch from `rpcbind.service` to `rpcbind.socket`, because enabling service actually enables the socket, and is-enabled shows the right thing for socket.

**Comment by landrypm** [comment] 2017-09-05 19:48
I am also still seeing this error on RHEL 7.

puppet-agent[1155]: (/Stage[main]/Nfs::Client::Service/Service[rpcbind.service]/enable) enable changed 'false' to 'true'

├── derdanne-nfs (v2.0.4)

puppet-agent-1.10.5-1.el7.x86_64

  class { '::nfs':
    server_enabled => false,
    client_enabled => true,
    nfs_v4_client => true,
    nfs_v4_idmap_domain => $::domain,
  }

**Comment by dylex** [comment] 2017-09-07 14:43
Hi @derdanne, can we re-open this or should we submit a new issue?

**Comment by derdanne** [comment] 2017-09-07 14:46
Hey, sorry for the delay - i will try to solve this issue in the next days. When i have enough time, i'll try to build some integration Test for CentOS.

**Comment by dylex** [comment] 2017-09-07 14:55
Thanks. I can confirm that using `rpcbind.socket` instead _almost_ fixes this: enabling `rpcbind.socket` indirectly enables `rpcbind.service`, and `systemctl is-enabled rpcbind.socket` returns the right answer. However, starting `rpcbind.socket` does not start `rpcbind.service`, so while it will come up correctly by default (e.g., on the next restart), `systemctl start rpcbind.socket` won't actually start `rpcbind` (but starting `rpcbind.service` will start `rpcbind.socket`).  So, one solution is to `ensure => running` on `rpcbind.service`, but only enable `rpcbind.socket`, and I'm not sure the best way to do that.

**Comment by derdanne** [comment] 2017-10-10 10:21
@dylex @landrypm 

Sorry for beeing late to the party ;)

I've added the changes to https://github.com/derdanne/puppet-nfs/tree/bugfix_rpcbind.service__default_domain

I could verify on CentOS 7, that this fix works. Puppet only starts the rpcbind.service once and mounting after system startup works. Can you check, if this fix has any drawbacks on RedHat 7?

**Comment by dylex** [comment] 2017-10-10 14:36
We're on Centos 7.4 but it works well for me there.

**Comment by landrypm** [comment] 2017-10-10 16:44
Initial tests on a RHEL 7.4 NFS client seem good. I am no longer getting the 
rpcbind service messages on every run. If I do stop rpcbind manually it does 
get restarted on the next puppet run. Subsequent runs do not display any 
messages about rpcbind. 

I will do more testing on an NFS server shortly. 

----- Original Message -----

> From: "Daniel Klockenkämper" <notifications@github.com>
> To: "derdanne/puppet-nfs" <puppet-nfs@noreply.github.com>
> Cc: "landrypm" <patrick.landry@louisiana.edu>, "Mention"
> <mention@noreply.github.com>
> Sent: Tuesday, October 10, 2017 5:21:24 AM
> Subject: Re: [derdanne/puppet-nfs] Service[rpcbind.service]/enable: enable
> changed 'false' to 'true' on every run. (#55)

> @dylex @landrypm

> Sorry for beeing late to the party ;)

> I've added the changes to
> https://github.com/derdanne/puppet-nfs/tree/bugfix_rpcbind.service__default_domain

> I could verify on CentOS 7, that this fix works. Puppet only starts the
> rpcbind.service once and mounting after system startup works. Can you check,
> if this fix has any drawbacks on RedHat 7?

> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub , or mute the thread .

-- 

	

Patrick Landry 
Director, UCSS 
University of Louisiana at Lafayette 
pml@louisiana.edu

**Comment by landrypm** [comment] 2017-10-10 18:30
Initial tests on an NFS server also seem to be successful. Thanks for the fix! 

----- Original Message -----

> From: "Dylan Simon" <notifications@github.com>
> To: "derdanne/puppet-nfs" <puppet-nfs@noreply.github.com>
> Cc: "landrypm" <patrick.landry@louisiana.edu>, "Mention"
> <mention@noreply.github.com>
> Sent: Tuesday, October 10, 2017 9:36:37 AM
> Subject: Re: [derdanne/puppet-nfs] Service[rpcbind.service]/enable: enable
> changed 'false' to 'true' on every run. (#55)

> We're on Centos 7.4 but it works well for me there.

> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub , or mute the thread .

-- 

	

Patrick Landry 
Director, UCSS 
University of Louisiana at Lafayette 
pml@louisiana.edu

**Comment by derdanne** [comment] 2017-10-10 21:15
merged to master

**Closed by derdanne** 2017-10-10 21:15 UTC
Labels: bug
