### ISSUE TITLE
Puppet Stuck Restarting RPCBind.Socket on Every Run

### ISSUE THREAD

**Issue by eatonc** [derdanne/puppet-nfs#82] opened 2018-06-04 19:19 UTC
Hi,

I setup an NFS v3 client using the following configuration on CentOS 7.4.1708:

`class {'::nfs':`
`     client_enabled => true,`
`      }`
`      nfs::client::mount {$target_directory:`
`        server      => $nfs_server,`
`        share       => $nfs_share,`
`        remounts    => $nfs_remounts,`
`        atboot      => $nfs_atboot,`
`        options_nfs => $nfs_options,`
`      }`

After Puppet installs the nfs-utils and nfs4-acl-tools packages, it attempts to restart the rpcbind.service and rpcbind.socket services. The rpcbind.service service is restarted successfully, but rpcbind.socket refuses with the following error:

> Notice: /Stage[main]/Nfs::Client::Package/Package[nfs-utils]/ensure: created
Info: /Stage[main]/Nfs::Client::Package/Package[nfs-utils]: Scheduling refresh of Service[rpcbind.service]
Info: /Stage[main]/Nfs::Client::Package/Package[nfs-utils]: Scheduling refresh of Service[rpcbind.socket]
Notice: /Stage[main]/Nfs::Client::Package/Package[nfs4-acl-tools]/ensure: created
Info: /Stage[main]/Nfs::Client::Package/Package[nfs4-acl-tools]: Scheduling refresh of Service[rpcbind.service]
Info: /Stage[main]/Nfs::Client::Package/Package[nfs4-acl-tools]: Scheduling refresh of Service[rpcbind.socket]
Notice: /Stage[main]/Nfs::Client::Service/Service[rpcbind.service]: Triggered 'refresh' from 2 events
Error: /Stage[main]/Nfs::Client::Service/Service[rpcbind.socket]: Failed to call refresh: Systemd restart for rpcbind.socket failed!
journalctl log for rpcbind.socket:
-- Logs begin at Wed 2018-05-30 13:20:59 CDT, end at Mon 2018-06-04 14:01:38 CDT. --
Jun 04 14:01:38 systemd[1]: Listening on RPCbind Server Activation Socket.
Jun 04 14:01:38 systemd[1]: Starting RPCbind Server Activation Socket.
Jun 04 14:01:38 systemd[1]: Stopping RPCbind Server Activation Socket.
Jun 04 14:01:38 systemd[1]: Socket service rpcbind.service already active, refusing.
Jun 04 14:01:38 systemd[1]: Failed to listen on RPCbind Server Activation Socket.
Error: /Stage[main]/Nfs::Client::Service/Service[rpcbind.socket]: Systemd restart for rpcbind.socket failed!
journalctl log for rpcbind.socket:
-- Logs begin at Wed 2018-05-30 13:20:59 CDT, end at Mon 2018-06-04 14:01:38 CDT. --
Jun 04 14:01:38 systemd[1]: Listening on RPCbind Server Activation Socket.
Jun 04 14:01:38 systemd[1]: Starting RPCbind Server Activation Socket.
Jun 04 14:01:38 systemd[1]: Stopping RPCbind Server Activation Socket.
Jun 04 14:01:38 systemd[1]: Socket service rpcbind.service already active, refusing.
Jun 04 14:01:38 systemd[1]: Failed to listen on RPCbind Server Activation Socket.
Info: Class[Nfs::Client::Service]: Unscheduling all events on Class[Nfs::Client::Service]
Notice: /Stage[main]/Nfs::Client/Anchor[nfs::client::end]: Dependency Service[rpcbind.socket] has failures: false
Warning: /Stage[main]/Nfs::Client/Anchor[nfs::client::end]: Skipping because of failed dependencies

Subsequent Puppet runs result in the same error trying to refresh the rpcbind services. If I manually stop the rpcbind.service service and run puppet, puppet starts the services as expected and the errrors cease.

However, manually attempting to restart the rpcbind.socket service with **systemctl restart rpcbind.socket** yields the same error,

> Socket service rpcbind.service already active, refusing.

As mentioned in [https://bugzilla.redhat.com/show_bug.cgi?id=1546700#c2](url), it appears this behavior is expected.

> when "service rpcbind.service (is) already active", the
"rpcbind.socket" restarting will be refused now. If we stop
"rpcbind.service" by hand and then restart "rpcbind.socket", _NO_ hang
occurs.

However, I'm struggling to get a clean puppet run without manual intervention with this being the case. For what it's worth, I'm running Puppet Enterprise 2017.3.2.  Any thoughts or assistance would be greatly appreciated.

Thanks,

CE

**Comment by eatonc** [comment] 2018-06-05 12:56
There might be a better way of doing this, but I was able to workaround this by using the puppetlabs/transition module. It still errors on the first puppet run, but a subsequent run completes cleanly.

[https://forge.puppet.com/puppetlabs/transition](url)

Code sample:
`transition {'stop-rpcbind.service-service':`
`    resource   => Service['rpcbind.service'],`
`    attributes => { ensure => stopped },`
`    prior_to   => Service['rpcbind.socket'],`
`  }`

**Comment by salderma** [comment] 2018-10-03 19:37
I can confirm this issue to be valid on CentOS 7.5.  I started using the module today for a webserver that will serve content from an NFS share.  I will follow @eatonc's work around for now, but would be happy to help test something if needed.

**Comment by derdanne** [comment] 2018-10-05 15:44
Hey @eatonc , i've added the branch https://github.com/derdanne/puppet-nfs/tree/stuck_restart_rpcbind-socket. I've added the dependency to the transition module and also the code you'va staded above. But i am not really lucky with it at the moment - i have to setup some testing for this case - maybe there comes another idea without using an external module.

@salderma  I am wondering that it tries to restart the rpcbind.socket in 7.5, since it should'nt be defined in Centos >=7.5, when i look at params.pp. Could you please give me the facter output for operatingsystemrelease, ostype and os. and also the output of your puppet agent.

**Comment by daniel-cole** [comment] 2018-10-15 08:32
@derdanne I was also facing this issue with CentOS 7.5. After testing the branch in one of our dev environments I can confirm the transition patch seems to work.
 
**facter output:**
_[root@host ~]# facter operatingsystemrelease_
`7.5.1804`

_[root@host ~]# facter os_

> {
  architecture => "x86_64",
  family => "RedHat",
  hardware => "x86_64",
  name => "CentOS",
  release => {
    full => "7.5.1804",
    major => "7",
    minor => "5"
  },
  selinux => {
    config_mode => "enforcing",
    config_policy => "targeted",
    current_mode => "enforcing",
    enabled => true,
    enforced => true,
    policy_version => "31"
  }
}

**puppet agent output:**

> Error: Systemd start for rpcbind.socket failed!
journalctl log for rpcbind.socket:
-- Logs begin at Mon 2018-10-15 15:52:10 AEDT, end at Mon 2018-10-15 19:20:37 AEDT. --
Oct 15 19:20:37 vm.local systemd[1]: Socket service rpcbind.service already active, refusing.
Oct 15 19:20:37 vm.local systemd[1]: Failed to listen on RPCbind Server Activation Socket.

> Error: /Stage[main]/Nfs::Client::Service/Service[rpcbind.socket]/ensure: change from 'stopped' to 'running' failed: Systemd start for rpcbind.socket failed!
journalctl log for rpcbind.socket:
-- Logs begin at Mon 2018-10-15 15:52:10 AEDT, end at Mon 2018-10-15 19:20:37 AEDT. --
Oct 15 19:20:37 vm.local systemd[1]: Socket service rpcbind.service already active, refusing.
Oct 15 19:20:37 vm.local systemd[1]: Failed to listen on RPCbind Server Activation Socket.

**Comment by derdanne** [comment] 2019-02-08 12:38
merged to develop

**Comment by derdanne** [comment] 2019-02-08 19:42
released in 2.1.0

**Closed by derdanne** 2019-02-08 19:42 UTC
Labels: bug
